on:
  pull_request:
    branches: 
      - develop
    types: [closed]

jobs:
  compile-frontend:
    if: ${{ github.event.pull_request.merged && !startsWith(github.event.pull_request.head.ref, 'auto-frontend-') }}
    name: Build Frontend
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v5
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
      - name: Install JSPacker
        run: go install vimagination.zapto.org/jspacker/cmd/jspacker@latest
      - name: Set up Node
        uses: actions/setup-node@v6
      - name: Install Terser
        run: npm i -g terser
      - name: Install zopfli
        run: sudo apt install -y zopfli
      - name: Compile Frontend
        id: compile
        working-directory: ./frontend
        run: bash embed.sh && { git diff --quiet HEAD -- index.html.gz && echo changed=false || echo changed=true; } >> $GITHUB_OUTPUT
      - name: Commit Frontend
        if: steps.compile.outputs.changed == 'true'
        uses: EndBug/add-and-commit@v9
        with:
          add: 'frontend'
          message: "Rebuilt Frontend"
          new_branch: auto-frontend-${{ github.run_number }}
      - name: Create PR
        if: steps.compile.outputs.changed == 'true'
        run: gh pr create --base develop --head auto-frontend-${{ github.run_number }} --title "[auto] Frontend Rebuild" --body "Autogenerated frontend build"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
