on:
  pull_request:
    branches: 
      - develop
    types: [closed]

jobs:
  compile-frontend:
    if: ${{ github.event.pull_request.merged }}
    name: Build Frontend
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v5
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
      - name: Install JSPacker
        run: go install vimagination.zapto.org/jspacker/cmd/jspacker@latest
      - name: Set up Node
        uses: actions/setup-node@v6
      - name: Install Terser
        run: npm i -g terser
      - name: Install zopfli
        run: sudo apt install -y zopfli
      - name: Compile Frontend
        working-directory: ./frontend
        run: bash embed.sh
      - name: Commit Frontend
        uses: EndBug/add-and-commit@v9
        with:
          add: 'frontend'
          message: "Rebuilt Frontend"